# Generated by Django 5.2 on 2025-05-12 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsportal', '0003_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
